KS-8-4 added: array of strings, print all ingredients, if condition and change ingredient. print new array
Elraden/KotlinSprint pull request #43
Opened 2024-12-29 10:43 UTC by Elraden

2024-12-30 06:32 UTC, ievetrovdev requested changes

2024-12-30 06:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task4.kt
> +    for (i in dishIngredients.indices) {
Переусложнил, можно по самим элементам массива проходить for (item in dishIngredients)

2024-12-30 06:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task4.kt
> +    if (userDishIngredient !in dishIngredients) {
Обрати внимание: `in` и `indexOf` делают одно и тоже - пробегаются по списку и ищут элемент. По идее нам должно хватить `indexOf` и переменной

2024-12-30 06:48 UTC, Elraden commented on src/main/kotlin/lesson_8/lesson8_task4.kt
> +    for (i in dishIngredients.indices) {
А как мне тогда проверить последний элемент массива, чтобы поставить в конце не ", ", а "]". Можно сделать проверку внутри цикла с indexOf, но получится примерно тоже самое

2025-01-04 14:02 UTC, ievetrovdev approved these changes

2025-01-04 14:03 UTC, merged