KS-10-3 added: user variable, function with generate random password
Elraden/KotlinSprint pull request #52
Opened 2024-12-30 19:55 UTC by Elraden

2025-01-16 21:44 UTC, ievetrovdev requested changes

2025-01-16 21:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +        val randomSymbol = " !\"#\$%&'()*+,-./".random()
По символам можно также итерироваться. Посмотри на вот эту табличку и попробуй найти закономерность) https://www.industrialnets.ru/files/misc/ascii.pdf

2025-01-17 09:13 UTC, Elraden commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +        val randomSymbol = " !\"#\$%&'()*+,-./".random()
Неожиданный для меня вариант, но очень удобный

2025-01-18 10:44 UTC, ievetrovdev approved these changes
Все верно, отлично!

2025-01-18 11:50 UTC, merged